#!/bin/sh

. /etc/rc.subr

name=zbackupd
rcvar=zbackupd_enable
zbackupd_config=`sed -n 's/zbackupd_config="\(.*\)"/\1/gp' /etc/rc.conf`
zbackupd_config=$(zbackupd_config:-"/usr/local/etc/zbackupd.yaml"}

command="/usr/local/bin/zbackupd"
command_args="-d -c $zbackupd_config > /var/log/zbackup.log"

load_rc_config $name
run_rc_command "$1"
